spring:
  cloud:
    function:
      definition: alertPatientPatientIdSupplier;patientDataRawPatientIdHrConsumer;patientDataRawPatientIdBpConsumer
    stream:
      bindings:
        alertPatientPatientIdSupplier-out-0:
          destination: 'alert/patient/{patient_id}'
        patientDataRawPatientIdHrConsumer-in-0:
          destination: patient/data/raw/*/hr
          group: cgp1
          consumer:
            concurrency: 1
        patientDataRawPatientIdBpConsumer-in-0:
          destination: patient/data/raw/*/bp
          group: cgp2
          consumer:
            concurrency: 1
      binders:
        solace-binder:
          type: solace
          environment:
            solace:
              java:
                host: 'localhost:5555'
                msgVpn: default
                clientUsername: default
                clientPassword: default
logging:
  level:
    root: info
    org:
      springframework: info

